#version: '2'

services:
  server:
    build: .
    container_name: wireguard
    image: tgiesela/wireguard:v0.1
    volumes:
      - /docker/data/wireguard:/etc/wireguard
#      - /lib/modules:/lib/modules
#      - /usr/src:/usr/src
    network_mode: host
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=Europe/Amsterdam
    restart: always

